@host = http://127.0.0.1:8000


POST {{host}}/task/ HTTP/1.1
content-type: application/json

{
    "task_name": "criar caso de teste com response",
    "task_status": "Doing",
    "description": "almost done",
    "is_active" : true,
    "user_id" : 1,
    "tags": ["doing", "python"]
}
###

GET {{host}}/task/list HTTP/1.1
content-type: application/json
###


GET {{host}}/task/0 HTTP/1.1
content-type: application/json
###